config/routes.rb
MarketApi::Application.routes.draw do
  get '/login' => 'v1/market#login'
  match '/auth/:provider/callback' => 'v1/sessions#create'
  post 'sessions/create' => "v1/sessions#create"

  get "/users/return_token", :to => "v1/users#return_token",          :as => "users_return_token"
  get "/users/check_logged_in", :to => "v1/users#check_logged_in",    :as => "check_logged_in"

  devise_for :users, :controllers => {:registrations => "v1/registrations", :sessions => "v1/my_devise_sessions"}

  namespace :admin do
    match "login/change" => "login#change"
    match "logout" => "login#destroy"

    resources :login

    match "pobs/search", :to => "pobs#search"
    resources :pobs do
      resources :coupons
      resources :banners
    end
    match "pobs/coupons/search", :to => "coupons#search"
    match "pobs/banners/search", :to => "banners#search"
    match "pobs/remove_pob_image/:pob_image_id", :to => "pobs#remove_pob_image"

    match "tours/:type/show_tours/:page", :to => "tours#show_tours", :as => "tours_show_tours"
    match "tours/pending", :to => "tours#pending"
    match "tours/rebuild_bundles", :to => "tours#rebuild_bundles"
    resources :tours do
      member do
        post :free
        post :paid
        post :publish
        post :unpublish
      end
    end

    match "clients/:id/save_tours", :to => "clients#save_tours", :as => "clients_save_tours"
    match "clients/:id/generate_users", :to => "clients#generate_users", :as => "clients_generate_users"
    match "clients/:id/show_users/:page", :to => "clients#show_users", :as => "clients_show_users"

    match "clients/check_name_validity", :to => "clients#check_name_validity"
    match "clients/check_password_validity", :to => "clients#check_password_validity"
    match "clients/check_email_validity", :to => "clients#check_email_validity"

    match "clients/:id/download_csv_userlist(/:generation)", :to => "clients#download_csv_userlist", :as => "clients_download_csv_userlist"
    match "clients/:id/download_pdf_userlist(/:generation)", :to => "clients#download_pdf_userlist", :as => "clients_download_pdf_userlist"

    resources :clients

    match "users/:type/show_users/:page", :to => "users#show_users", :as => "users_show_users"
    
    resources :users do
      resources :orders
    end

    resource :dashboard

    resource :statistics, :only => [] do
      member do
        get :top_buyers
        get :top_popular_tours
      end
    end
    root :to => 'dashboard#index'
  end

  namespace :v1 do
    namespace :ios do
      resources :orders, :only => :create
    end
    namespace :android do
      resources :orders, :only => :create
    end
    
    resources :orders, :only => [:index, :show]
    resources :places, :only => :index
    resources :clients, :only => :index
    resources :pob_categories, :only => :index
  end

  get '/pobs/create_bundle' => "v1/pobs#create_bundle"
  get '/pobs/sync' => "v1/pobs#sync"

  get '/market/places/:country/:city.xml' => "v1/market#show",               :as => "market_country_city"
  get '/market/places/:country.xml' => "v1/market#show"
  get '/market/places.xml' => "v1/market#index"

  match "/products/map/:id.:format" => "v1/products#map",                    :as => "map_market_product"
  match "/products/media/:id.:format" => "v1/products#media",                :as => "media_market_product"
  match "/products/:id.:format" => "v1/products#show",                       :as => "market_product"

  root :to => "admin/dashboard#index"
end

app/models/client.rb
class Client < ActiveRecord::Base
  validates_presence_of :name, :email
  validates_uniqueness_of :email, :name
  validates_length_of :password, :minimum => 6, :on => :update
  validates :email, :exclusion => {:in => MarketApi::Application.config.reserved_emails,  :message => "%{value} is reserved"}

  has_many :tours
  has_many :users

  attr_accessor :merge_existing_user

  before_create :generate_api_key_and_password
  after_create :create_user_with_preview_rights
  before_create :check_if_user_with_the_same_email_present

  EMAIL_PATTERN = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/

  validates_format_of :email, :with => EMAIL_PATTERN

  def generated_users
    self.users.where(:is_preview_user => false)
  end

  def preview_user
    self.users.where(:is_preview_user => true).first
  end

  def generate_api_key_and_password
    password_symbols = (["A".."Z", "a".."z", 1..9].map(&:to_a).flatten + ['!','$'])
    self.api_key = Devise.friendly_token[0,20]
    self.password = password_symbols.sample(7).join
  end

  def check_if_user_with_the_same_email_present
    if User.find_by_email(self.email) && ! self.merge_existing_user
      self.errors.add :user_email_conflict, "You are registering client with email which is belong to user. Do you want merge accounts and reset user's password?"
      false
    else
      true
    end
  end

  def create_user_with_preview_rights
    self.reload

    user = if self.merge_existing_user
      u = User.find_by_email self.email
      u.update_attributes :password => self.password, :is_preview_user => true
      u.reload
      u
    else
      User.create!(:email => self.email, :password => self.password, :is_preview_user => true)
    end

    self.users << user
  end
end

app/controllers/admin/clients_controller.rb
class Admin::ClientsController < Admin::ApplicationController
  NUM_OF_USERS_PER_PAGE = 50
  include ERB::Util

  skip_before_filter :request_auth, :only => [:check_validity]

  def index
    @clients = Client.all
    @client = Client.new
  end

  def create
    @client = Client.new :name => params[:user_name], :email => params[:email_address], :merge_existing_user => (params[:merge_user] == 'true')
    if @client.save
      # automatically creates user with preview rights on after_save action
      flash[:notice] = "The client #{h params[:user_name]} was successfully created. It'll be available in Tour Builder after 5 minutes"
      if ! request.xhr?
        redirect_to admin_client_path(@client.id)
      end
    end
  end

  def check_validity
    @client = Client.new :name => params[:user_name], :email => params[:email_address]
    @client.valid?
  end

  def check_email_validity
    if params[:client_id]
      @client = Client.find params[:client_id]
    end

    @message = if params[:email_address].blank?
      "<li>Email can't be blank</li>"
    elsif params[:email_address] !~ Client::EMAIL_PATTERN
      "<li>Email is invalid</li>"
    elsif (!@client && Client.find_by_email(params[:email_address])) || (@client && params[:email_address] != @client.email && Client.find_by_email(params[:email_address]))
      "<li>Email has already been taken</li>"
    end
  end

  def check_name_validity
    if params[:client_id]
      @client = Client.find params[:client_id]
    end

    @message = if params[:user_name].blank?
      "<li>Name can't be blank</li>"
    elsif (!@client && Client.find_by_name(params[:user_name])) || (@client && params[:user_name] != @client.name && Client.find_by_name(params[:user_name]))
      "<li>Name has already been taken</li>"
    end
  end

  def check_password_validity
    @message = if params[:user_password].to_s.length < 6
      "<li>Password is too short (minimum is 6 characters)</li>"
    end
  end

  def edit
    @client = Client.find params[:id]
    @available_tours = Tour.all
    @client_tour_ids = @client.tours.collect{|t| t.id}

    @current_page = 1
    @num_of_pages = (@client.users.count / NUM_OF_USERS_PER_PAGE.to_f).ceil
    @client_users = @client.users.order("created_at DESC").limit(NUM_OF_USERS_PER_PAGE)
  end

  def show
    @client = Client.find params[:id]
    @available_tours = Tour.all
    @client_tour_ids = @client.tours.collect{|t| t.id}

    @current_page = 1
    @num_of_pages = (@client.generated_users.count / NUM_OF_USERS_PER_PAGE.to_f).ceil
    @client_users = @client.generated_users.order("created_at DESC").limit(NUM_OF_USERS_PER_PAGE)
  end

  def update
    @client = Client.find params[:id]
    if @client.update_attributes(params[:client])
      @client.reload
      preview_user = @client.preview_user
      preview_user.email = @client.email
      preview_user.password = @client.password
      preview_user.save
      flash[:notice] = "The client's record was successfully updated! All changes will be applied in Tour Builder after 5 minutes"

      if ! request.xhr?
        redirect_to admin_client_path(@client.id)
      end
    end
  end

  def destroy
    @client = Client.find params[:id]
    if @client.destroy
      redirect_to admin_clients_path, :notice => "The client '#{@client.name}' was successfully deleted"
    else
      redirect_to admin_client_path(@client.id), :error => "There were some errors while deleting specified client"
    end
  end

  def generate_users
    client = Client.find params[:id]
    client_domain = client.email.match(/.*@(.*)/)[1]
    Rails.logger.warn 'cl match ' + client.email.match(/.*@(.*)/).inspect
    client.update_attribute(:last_generation_index, (client.last_generation_index + 1))
    client.reload
    symbols = ["A".."Z", "a".."z", 1..9].map(&:to_a).flatten
    params[:quantity].to_i.times do |i|
      user = User.new
      user.name = symbols.sample(10).join
      user.email = "#{user.name}@#{client_domain}"
      user.password = user.name
      user.generation_index = client.last_generation_index
      user.save

      client.users << user
    end
    redirect_to admin_client_path(client.id)
  end

  def save_tours
    client = Client.find params[:id]

    if ! params[:tour_id].blank?
      params[:tour_id].each do |tour_id|
        tour = Tour.find(tour_id)
        tour.update_attribute :client_id, client.id
      end
    else
      client.tours.each{|tour| tour.update_attribute :client_id, nil}
    end
    redirect_to admin_client_path(client.id)
  end

  def show_users
    @client = Client.find params[:id]
    @current_page = params[:page]
    @num_of_pages = (@client.generated_users.count / NUM_OF_USERS_PER_PAGE.to_f).ceil
    @client_users = @client.generated_users.order("created_at DESC").limit(NUM_OF_USERS_PER_PAGE).offset((@current_page.to_i - 1) * NUM_OF_USERS_PER_PAGE)
  end

  def download_csv_userlist
    require 'csv'
    client = Client.find params[:id]

    if params[:generation].blank?
      client_users = client.users.without_preview
    else
      client_users = client.users.without_preview.generation(params[:generation])
    end

    if RUBY_VERSION.split('.')[1] == '9'
      csv_str = CSV::generate() do |csv|
        client_users.each do |user|
          csv << [user.email, user.name, user.created_at.to_s(:db)]
        end
      end
      send_data csv_str, :filename => "#{client.name}_users_list_#{Time.now.to_date}.csv"
    else
      f = String.new
      CSV::Writer.generate(f) do |csv|
        client_users.each do |user|
          csv << [user.email, user.name, user.created_at.to_s(:db)]
        end
      end
      send_data f, :filename => "#{client.name}_users_list_#{Time.now.to_date}.csv"
    end
  end

  def download_pdf_userlist
    client = Client.find params[:id]
    client.users.each do |user|
    end
  end
end

app/controllers/v1/clients_controller.rb
class V1::ClientsController < ApplicationController
  skip_before_filter :authenticate_by_token!
  before_filter :request_auth

  def index
    @clients = Client.all
    respond_to do |format|
      format.js { render :json => @clients.to_json }
    end
  end

  private
  def request_auth
    authenticate_or_request_with_http_basic do |login, passwd|
      login == TB_SYNC_LOGIN && passwd == TB_SYNC_PASSWD
    end
  end
end

app/views/admin/clients/_associated_tours.html.erb
<div style="background-color:#FFF;width:99%;margin-top:10px;border:1px solid #CCC;border-radius:5px; -moz-border-radius: 5px;padding:5px;">
  <div style="float:left"><h3>Associated Tours</h3></div>
  <!--div style="float:right"><a href="#" data-controls-modal="associate_tours_modal_dialog" class="btn primary">Add Tours</a></div-->
  <% if ! @client.tours.empty? %>
    <div style="clear:both"></div>
    <table class="table table-striped">
      <thead>
        <th>ID</th><th>Name</th><th>Status</th><th>Created</th>
      </thead>
      <tbody>
      <% @client.tours.each do |tour| %>
      <tr>
        <td><%= tour.id %></td>
        <td><%= tour.name %></td>
        <td><%= tour.status %></td>
        <td><%= tour.created_at.to_date %></td>
      </tr>
      <% end %>
      </tbody>
    </table>
  <% else %>
    <div style="clear:both"></div>
    <div>No associated tours.</div>
  <% end %>
</div>

app/views/admin/clients/_associated_tours_modal_dialog.html.erb
<div id="associate_tours_modal_dialog" class="modal hide fade">
  <div class="modal-header">
    <a href="#" class="close">&times;</a>
    <h3><%= @client.name %>: Add Tour</h3>
  </div>
  <%= form_tag admin_clients_save_tours_path(@client.id) do %>
  <div class="modal-body" style="height:400px;overflow:auto;">
    <table class="zebra-striped">
      <thead>
        <th>ID</th><th>Name</th><th>Status</th><th>Created</th><th>Action</th>
      </thead>
      <tbody>
        <% @available_tours.each do |tour| %>
          <tr>
            <td><%= tour.id %></td>
            <td><%= tour.name %></td>
            <td><%= tour.status %></td>
            <td><%= tour.created_at.to_date %></td>
            <td><input type="checkbox" name="tour_id[]" value="<%= tour.id %>" <%= @client_tour_ids.include?(tour.id) ? 'checked="checked"' : '' %>/></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="modal-footer">
    <div style="float:right;margin-left:10px;margin-top:5px;">or
      <a href="#" onclick="$('#associate_tours_modal_dialog').modal('hide')">Cancel</a>
    </div>
    <button class="btn primary">Save</button>
  </div>
  <% end %>
</div>

app/views/admin/clients/_associated_users.html.erb
<div style="background-color:#FFF;width:99%;margin-top:10px;border:1px solid #CCC;border-radius:5px; -moz-border-radius: 5px;padding:5px;">
  <div style="float:left"><h3>Generated Users</h3></div>

  <% if ! @client_users.empty? %>
    <div style="clear:both"></div>
    <div id="associated_users_container">
    <%= render :partial => "associated_users_core" %>
    </div>
  <% else %>
    <div style="clear:both"></div>
    <div>No generated users.</div>
  <% end %>
</div>

app/views/admin/clients/_associated_users_core.html.erb
<table class="table table-striped">
  <thead><th>Generation index</th><th>Number of generated users</th><th>Created at</th><th>Download as .csv</th></thead>
  <tbody>
  <% @client_users.group_by(&:generation_index).sort_by{|u| u[0]}.reverse.each do |u| %>
    <tr>
      <td><%= u[0] %></td>
      <td><%= u[1].count %></td>
      <td><%= u[1][0].created_at %></td>
      <td><%= link_to "Download as .csv", admin_clients_download_csv_userlist_path(@client.id, u[0]),:class => "btn primary" %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<%# if @client.users.count > Admin::ClientsController::NUM_OF_USERS_PER_PAGE %>
<!--div class="pagination">
  <ul>
    <li class="prev <%= @current_page.to_i == 1 ? 'disabled' : '' %>">
      <%= link_to raw('&larr; Previous'), admin_clients_show_users_path(@client.id, (@current_page.to_i - 1)), {:remote => true} %>
    </li>
    <% @num_of_pages.times do |i| %>
      <li <%= (@current_page.to_i == (i+1)) ? "class='active'" : '' %>><%= link_to (i + 1), admin_clients_show_users_path(@client.id, (i+1)), {:remote => true} %></li>
    <% end %>
    <li class="next <%= @current_page.to_i == @num_of_pages ? 'disabled' : '' %>">
      <%= link_to raw('Next &rarr;'), admin_clients_show_users_path(@client.id, (@current_page.to_i + 1)), {:remote => true} %>
    </li>
  </ul>
</div-->
<%# end %>

app/views/admin/clients/_delete_client_modal_dialog.html.erb
<div id="delete_client_modal_dialog" class="modal hide fade">
  <div class="modal-header">
    <a href="#" class="close">&times;</a>
    <h3>Delete Client?</h3>
  </div>
  <div class="modal-body">
    <p>Are you sure you want to delete client?</p>
  </div>
  <div class="modal-footer">
    <div style="float:right;margin-left:10px;margin-top:5px;">or
      <a href="#" onclick="$('#delete_client_modal_dialog').modal('hide')">Cancel</a>
    </div>
    <%= link_to "Delete Client", admin_client_path(@client.id), :method => :delete, :class => "btn danger" %>
  </div>
</div>

app/views/admin/clients/_notice.html.erb
<% [:notice, :error].each do |flash_type| %>
  <% if ! flash[flash_type].blank? %>
  <div class="alert alert-<%= flash_type == :notice ? 'success' : 'error' %>">
    <a class="close" href="#" onclick="jQuery(this).parent().fadeOut('slow')">×</a>
    <p><%= flash[flash_type] %></p>
  </div>
  <div style="clear:both"></div>
  <% end %>
<% end %>

app/views/admin/clients/check_email_validity.js.erb
if(! closing_add_client_modal_dialog) {
  jQuery('.email_address_errors').html('<%= raw escape_javascript(@message) %>');
  closing_add_client_modal_dialog = false;
}

app/views/admin/clients/check_name_validity.js.erb
if(! closing_add_client_modal_dialog) {
  jQuery('.user_name_errors').html('<%= raw escape_javascript(@message) %>');
  closing_add_client_modal_dialog = false;
}

app/views/admin/clients/check_password_validity.js.erb
jQuery('.user_password_errors').html('<%= raw escape_javascript(@message) %>');

app/views/admin/clients/create.js.erb
if(<%= ! @client.errors.empty? %>) {
  if(<%= ! @client.errors[:user_email_conflict].empty? %>) {
    jQuery('#merge_user_modal_dialog').modal({show:true});
  } else {
    jQuery('.email_address_errors').html('<%= raw @client.errors.full_messages.select{|m| m =~ /Email/}.collect{|m| "<li>#{escape_javascript(m)}</li>"}.first %>');
    jQuery('.user_name_errors').html('<%= raw @client.errors.full_messages.select{|m| m =~ /Name/}.collect{|m| "<li>#{escape_javascript(m)}</li>"}.first %>');
  }
} else {
  location.href = '/admin/clients/<%= @client.id %>';
}

app/views/admin/clients/edit.html.erb
<div style="float:left">
  <h3><%= link_to "Clients", admin_clients_path %>: <%= @client.name %></h3>
</div>
<!--div style="float:right">
  <a href="#" class="btn danger" data-controls-modal="delete_client_modal_dialog">Delete Client</a>
</div-->

<div style="clear:both"></div>

<div class="client_info">
  <h4>Edit Client Info</h4>
  <div class="details">
    <%= form_for @client, :url => admin_client_path(@client.id), :method => :put, :html => {:class => 'form-horizontal'}, :remote => true do |f| %>
      <div class="control-group">
        <label for="user_name" class="control-label">Client name:</label>
        <div class="controls">
          <%= f.text_field :name, :class => "xlarge", :id => "user_name", :onchange => "jQuery.post('/admin/clients/check_name_validity', {user_name: this.value, authenticity_token: '#{form_authenticity_token}', client_id: #{ @client.id }})" %>
          <div class="user_name_errors"></div>
        </div>
      </div>
      <div class="control-group">
        <label for="email_address" class="control-label">Email address:</label>
        <div class="controls">
          <%= f.text_field :email, :class => "xlarge", :id => "email_address", :onchange => "jQuery.post('/admin/clients/check_email_validity', {email_address: this.value, authenticity_token: '#{form_authenticity_token}', client_id: #{ @client.id }});" %>
          <div class="email_address_errors"></div>
        </div>
      </div>
      <div class="control-group">
        <label for="password" class="control-label">Password:</label>
        <div class="controls">
          <%= f.text_field :password, :class => "xlarge", :id => "user_password", :onchange => "check_password_validity(this.value, '#{form_authenticity_token}')" %>
          <div class="user_password_errors"></div>
        </div>
      </div>
      <div class="control-group">
        <label for="api_key" class="control-label">API key:</label>
        <div class="controls">
          <input type="text" value="<%=@client.api_key%>" class="xlarge disabled" id="api_key" disabled/>
        </div>
      </div>
      <div class="clearfix" class="control-label">
        <div style="text-align:center">
          <div class="span8"><input type="submit" class="btn btn-primary" value="Save"/>&nbsp;&nbsp;&nbsp;&nbsp;or&nbsp;<%= link_to "Cancel", admin_client_path(@client.id) %></span>
        </div>
      </div>

      <%#= render :partial => "associated_tours" %>

      <div style="clear:both"></div>
      <%#= render :partial => "associated_users" %>
    <% end %>
  </div>
</div>

<% if @client.tours.count == 0 %>
<%= render :partial => "delete_client_modal_dialog" %>
<% end %>

<%= render :partial => "associated_tours_modal_dialog" %>

app/views/admin/clients/show.html.erb
<div style="float:left">
  <h3><%= link_to "Clients", admin_clients_path %>: <%= @client.name %></h3>
</div>
<div style="float:right">
  <!--span style="">
    <a href="#" class="btn danger" data-controls-modal="delete_client_modal_dialog">Delete Client</a>
  <span-->
  <span style="margin-left:20px;">
    <%= link_to "Edit Client Info", edit_admin_client_path(@client.id), { :class => "btn btn-success" } %>
    <a href="#" class="btn btn-success" data-controls-modal="generate_hidden_users_modal_dialog">Generate Users</a>
    <a href="#" class="btn btn-primary" data-controls-modal="download_users_modal_dialog">Download All Users List</a>
  </span>
</div>

<div style="clear:both"></div>

<div class="client_info">
  <h4>Client Info</h4>
  <div class="details">
    <div class="row">
      <div class="span2">Client Name:</div>
      <div class="span3"><%= @client.name %></div>
      <div class="span2">Email Address:</div>
      <div class="span3"><%= @client.email %></div>
    </div>
    <div class="row">
      <div class="span2">Password:</div>
      <div class="span3"><%= @client.password %></div>
      <div class="span2">API key:</div>
      <div class="span3"><%= @client.api_key %></div>
    </div>
    <div class="row">
      <div class="span7"><small>* There is a preview user for this client with the same email/password</small></div>
    </div>

    <div style="clear:both"></div>

    <%= render :partial => "associated_tours" %>

    
    <div style="clear:both"></div>
    <%= render :partial => "associated_users" %>
  </div>
</div>

<% if @client.tours.count == 0 %>
<%= render :partial => "delete_client_modal_dialog" %>
<% end %>

<%= render :partial => "associated_tours_modal_dialog" %>

<%= render :partial => "generate_hidden_users_modal_dialog" %>

<div id="download_users_modal_dialog" class="modal hide fade">
  <div class="modal-header">
    <a href="#" class="close">&times;</a>
    <h3><%= @client.name %>: Download Users List</h3>
  </div>
  <div class="modal-body">
    <div style="text-align:center">
      <%= link_to "Download as .csv", admin_clients_download_csv_userlist_path(@client.id), :onclick => "$('#download_users_modal_dialog').modal('hide')",:class => "btn primary" %>
    </div>
  </div>
  <div class="modal-footer">
    <div style="float:right;margin-left:10px;margin-top:5px;">
      <a href="#" onclick="$('#download_users_modal_dialog').modal('hide')">Cancel</a>
    </div>
  </div>
</div>

app/views/admin/clients/show_users.js.erb
jQuery('#associated_users_container').html('<%= escape_javascript(render(:partial => 'associated_users_core')) %>');

app/views/admin/clients/update.js.erb
if(<%= ! @client.errors.empty? %>) {
  jQuery('.email_address_errors').html('<%= raw @client.errors.full_messages.select{|m| m =~ /Email/}.collect{|m| "<li>#{escape_javascript(m)}</li>"}.first %>');
  jQuery('.user_name_errors').html('<%= raw @client.errors.full_messages.select{|m| m =~ /Name/}.collect{|m| "<li>#{escape_javascript(m)}</li>"}.first %>');
  jQuery('.user_password_errors').html('<%= raw @client.errors.full_messages.select{|m| m =~ /Password/}.collect{|m| "<li>#{escape_javascript(m)}</li>"}.first %>');
} else {
  location.href = '/admin/clients/<%= @client.id %>';
}