config/routes.rb
MarketApi::Application.routes.draw do
  get '/login' => 'v1/market#login'
  match '/auth/:provider/callback' => 'v1/sessions#create'
  post 'sessions/create' => "v1/sessions#create"

  get "/users/return_token", :to => "v1/users#return_token",          :as => "users_return_token"
  get "/users/check_logged_in", :to => "v1/users#check_logged_in",    :as => "check_logged_in"

  devise_for :users, :controllers => {:registrations => "v1/registrations", :sessions => "v1/my_devise_sessions"}

  namespace :admin do
    match "login/change" => "login#change"
    match "logout" => "login#destroy"

    resources :login

    match "pobs/search", :to => "pobs#search"
    resources :pobs do
      resources :coupons
      resources :banners
    end
    match "pobs/coupons/search", :to => "coupons#search"
    match "pobs/banners/search", :to => "banners#search"
    match "pobs/remove_pob_image/:pob_image_id", :to => "pobs#remove_pob_image"

    match "tours/:type/show_tours/:page", :to => "tours#show_tours", :as => "tours_show_tours"
    match "tours/pending", :to => "tours#pending"
    match "tours/rebuild_bundles", :to => "tours#rebuild_bundles"
    resources :tours do
      member do
        post :free
        post :paid
        post :publish
        post :unpublish
      end
    end

    match "clients/:id/save_tours", :to => "clients#save_tours", :as => "clients_save_tours"
    match "clients/:id/generate_users", :to => "clients#generate_users", :as => "clients_generate_users"
    match "clients/:id/show_users/:page", :to => "clients#show_users", :as => "clients_show_users"

    match "clients/check_name_validity", :to => "clients#check_name_validity"
    match "clients/check_password_validity", :to => "clients#check_password_validity"
    match "clients/check_email_validity", :to => "clients#check_email_validity"

    match "clients/:id/download_csv_userlist(/:generation)", :to => "clients#download_csv_userlist", :as => "clients_download_csv_userlist"
    match "clients/:id/download_pdf_userlist(/:generation)", :to => "clients#download_pdf_userlist", :as => "clients_download_pdf_userlist"

    resources :clients

    match "users/:type/show_users/:page", :to => "users#show_users", :as => "users_show_users"
    
    resources :users do
      resources :orders
    end

    resource :dashboard

    resource :statistics, :only => [] do
      member do
        get :top_buyers
        get :top_popular_tours
      end
    end
    root :to => 'dashboard#index'
  end

  namespace :v1 do
    namespace :ios do
      resources :orders, :only => :create
    end
    namespace :android do
      resources :orders, :only => :create
    end
    
    resources :orders, :only => [:index, :show]
    resources :places, :only => :index
    resources :clients, :only => :index
    resources :pob_categories, :only => :index
  end

  get '/pobs/create_bundle' => "v1/pobs#create_bundle"
  get '/pobs/sync' => "v1/pobs#sync"

  get '/market/places/:country/:city.xml' => "v1/market#show",               :as => "market_country_city"
  get '/market/places/:country.xml' => "v1/market#show"
  get '/market/places.xml' => "v1/market#index"

  match "/products/map/:id.:format" => "v1/products#map",                    :as => "map_market_product"
  match "/products/media/:id.:format" => "v1/products#media",                :as => "media_market_product"
  match "/products/:id.:format" => "v1/products#show",                       :as => "market_product"

  root :to => "admin/dashboard#index"
end

app/models/pob.rb
class Pob < ActiveRecord::Base
  has_and_belongs_to_many :pob_categories
  has_many :pob_images
  has_many :coupons, :dependent => :destroy
  has_many :banners, :dependent => :destroy

  validates_associated :pob_categories
  validates_presence_of :name, :country, :pob_categories
  validates_presence_of :longitude, :latitude, :address, :unless => lambda {|pob| pob.draft?}

  accepts_nested_attributes_for :pob_images, :reject_if => :all_blank, :allow_destroy => true

  attr_accessible :pob_images, :url, :country, :name, :city, :address, :longitude, :latitude, :pob_category_ids, :description, :icon, :icon_cache, :image_cache, :pob_images_attributes, :price_range, :open_hours, :email, :phone, :txt_file

  # carrierwave
  mount_uploader :icon, IconUploader
  mount_uploader :txt_file, PobTxtUploader

  attr_writer :draft # defined to determine whether this POB is added through script to draft categories or it's 
                       # added manually

  after_save :find_affected_tours
  after_save :xmlize_txt_file, :unless => lambda {|pob| pob.txt_file.blank?}

  before_destroy :find_affected_tours

  def xmlize_txt_file
    # please forgive me
    txt = File.read(self.txt_file.path)
    if txt[0..4] == '<?xml'
      return
    end

    xmlized_content = ""
    xml = Builder::XmlMarkup.new(:target => xmlized_content)
    xml.instruct!
    xml.data do
      xml.text do |t|
        t << self.txt_file.read   #  doing 't << value' rather then 'xml.text value' will save the value w/o encoding into html entities
      end
    end
    File.open(self.txt_file.path, 'w') do |f|
      f.write xmlized_content.force_encoding("UTF-8")
    end
  end
  
  def find_affected_tours
    affected_pob_bundles = PobsBundle.where(['south <= :lat AND 
                                              north >= :lat AND 
                                              west <= :long AND 
                                              east >= :long', 
                                              {:lat => self.latitude, :long => self.longitude}]).all
    if !affected_pob_bundles.blank?
      affected_pob_bundles.each do |pob_bundle|
        # if at least one category matched
        intersection = self.pob_categories.map(&:id) & pob_bundle.filtered_categories
        if !intersection.empty?
          pob_bundle.tour.try(:touch!)
        end
      end
    end
  end

  def draft?
    !! @draft
  end
end

app/controllers/admin/pobs_controller.rb
COUNTRIES = ["Afghanistan", "Aland Islands", "Albania", "Algeria", "American Samoa", "Andorra", "Angola",
        "Anguilla", "Antarctica", "Antigua And Barbuda", "Argentina", "Armenia", "Aruba", "Australia", "Austria",
        "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin",
        "Bermuda", "Bhutan", "Bolivia, Plurinational State of", "Bonaire, Sint Eustatius and Saba", "Bosnia and Herzegovina",
				"Botswana", "Bouvet Island", "Brazil",
        "British Indian Ocean Territory", "Brunei Darussalam", "Bulgaria", "Burkina Faso", "Burundi", "Cambodia",
        "Cameroon", "Canada", "Cape Verde", "Cayman Islands", "Central African Republic", "Chad", "Chile", "China",
        "Christmas Island", "Cocos (Keeling) Islands", "Colombia", "Comoros", "Congo",
        "Congo, the Democratic Republic of the", "Cook Islands", "Costa Rica", "Cote d'Ivoire", "Croatia", "Cuba",
        "Cyprus", "Czech Republic", "Denmark", "Djibouti", "Dominica", "Dominican Republic", "Ecuador", "Egypt",
        "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Ethiopia", "Falkland Islands (Malvinas)",
        "Faroe Islands", "Fiji", "Finland", "France", "French Guiana", "French Polynesia",
        "French Southern Territories", "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Gibraltar", "Greece",
				"Greenland", "Grenada", "Guadeloupe", "Guam", "Guatemala", "Guernsey", "Guinea",
        "Guinea-Bissau", "Guyana", "Haiti", "Heard Island and McDonald Islands", "Holy See (Vatican City State)",
        "Honduras", "Hong Kong", "Hungary", "Iceland", "India", "Indonesia", "Iran, Islamic Republic of", "Iraq",
        "Ireland", "Isle of Man", "Israel", "Italy", "Jamaica", "Japan", "Jersey", "Jordan", "Kazakhstan", "Kenya",
        "Kiribati", "Korea, Democratic People's Republic of", "Korea, Republic of", "Kuwait", "Kyrgyzstan",
        "Lao People's Democratic Republic", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya",
        "Liechtenstein", "Lithuania", "Luxembourg", "Macao", "Macedonia, The Former Yugoslav Republic Of",
        "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Martinique",
        "Mauritania", "Mauritius", "Mayotte", "Mexico", "Micronesia, Federated States of", "Moldova, Republic of",
        "Monaco", "Mongolia", "Montenegro", "Montserrat", "Morocco", "Mozambique", "Myanmar", "Namibia", "Nauru",
        "Nepal", "Netherlands", "New Caledonia", "New Zealand", "Nicaragua", "Niger",
        "Nigeria", "Niue", "Norfolk Island", "Northern Mariana Islands", "Norway", "Oman", "Pakistan", "Palau",
        "Palestinian Territory, Occupied", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines",
        "Pitcairn", "Poland", "Portugal", "Puerto Rico", "Qatar", "Reunion", "Romania", "Russian Federation",
        "Rwanda", "Saint Barthelemy", "Saint Helena, Ascension and Tristan da Cunha", "Saint Kitts and Nevis", "Saint Lucia",
        "Saint Martin (French Part)", "Saint Pierre and Miquelon", "Saint Vincent and the Grenadines", "Samoa", "San Marino",
        "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore",
        "Sint Maarten (Dutch Part)", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa",
        "South Georgia and the South Sandwich Islands", "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname",
        "Svalbard and Jan Mayen", "Swaziland", "Sweden", "Switzerland", "Syrian Arab Republic",
        "Taiwan, Province of China", "Tajikistan", "Tanzania, United Republic of", "Thailand", "Timor-Leste",
        "Togo", "Tokelau", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan",
        "Turks and Caicos Islands", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom",
        "United States", "United States Minor Outlying Islands", "Uruguay", "Uzbekistan", "Vanuatu",
				"Venezuela, Bolivarian Republic of", "Viet Nam", "Virgin Islands, British", "Virgin Islands, U.S.",
				"Wallis and Futuna", "Western Sahara", "Yemen", "Zambia", "Zimbabwe"]

class Admin::PobsController < Admin::ApplicationController

  before_filter :set_defaults, :only => [:create, :update, :new, :edit]

  def index
    @page = params[:page] || 1
    @pobs = Pob.includes([:pob_categories]).order('created_at DESC').paginate(:page => @page, :per_page => 30)
    @pobs_count = Pob.count
    @countries = COUNTRIES
  end

  def search
    relation = Pob.includes([:pob_categories]).order('pobs.created_at DESC')

    @pob_name = params[:pob][:name]
    @pob_country = params[:pob][:country]
    @pob_city = params[:pob][:city]
    @pob_category = params[:pob][:category]

    relation = @pob_name.blank? ? relation : relation.where(['pobs.name LIKE ?', "%#{@pob_name}%"])
    relation = @pob_category.blank? ? relation : relation.where(['pob_categories_pobs.pob_category_id IN (?)', @pob_category])
    relation = @pob_country.blank? ? relation : relation.where(['country = ?', @pob_country])
    relation = @pob_city.blank? ? relation : relation.where(['city LIKE ?', "%#{@pob_city}%"])

    @page = params[:page] || 1
    @pobs_count = relation.count
    @pobs = relation.paginate(:page => @page, :per_page => 30)
    @countries = COUNTRIES

    render :index
  end

  def show
    @pob = Pob.find params[:id]
  end

  def edit
    @pob = Pob.find params[:id]
    session[:return_to_pob] = request.env["HTTP_REFERER"]
  end

  def destroy
    @pob = Pob.find params[:id]
    if @pob.destroy
      set_flash_notice @pob, "deleted"
      redirect_to admin_pobs_url
    else
      flash[:error] = "Sorry, there were errors while deleting new Place of Business"
      redirect_to(:back)
    end
  end

  def new
    @pob = Pob.new
    session[:return_to_pob] = request.env["HTTP_REFERER"]
  end

  def update
    @pob = Pob.find(params[:id])
    if @pob.update_attributes(params[:pob])
      set_flash_notice @pob, "updated"
      redirect_to admin_pobs_url(@pob.id)
    else
      flash.now[:error] = "Sorry, there were errors while updating #{@pob.name}"
      render(:action => :edit)
    end
  end

  def create
    @pob = Pob.new(params[:pob])  
    if !@pob.save
      flash.now[:error] = "Sorry, there were errors while creating new Place of Business"
      render(:action => :new)
    else
      flash[:notice] = "You've successfully created Place of Business called #{@pob.name}"
      set_flash_notice @pob, "created"
      redirect_to admin_pobs_url(@pob.id)
    end
  end

  def remove_pob_image
    pob_image = PobImage.find_by_id(params[:pob_image_id])
    pob_image.remove_image!
    pob_image.destroy
    render :json => {:result => "ok"}.to_json    
  rescue
    render :json => {:result => "failed"}.to_json, :status => 500
  end

  def remove_pob_icon
    pob = Pob.find_by_id(params[:pob_id])
    pob.remove_icon! if pob
  end

  private

    def set_defaults
      @top_categories = PobCategory.where('parent_id IS NULL').all
      @countries = COUNTRIES
    end

    def set_flash_notice(pob, action)
        flash[:notice] = "You've successfully #{action} Place of Business called #{pob.name}. ".html_safe
        if Tour.edited.count > 0
          flash[:notice] << "<br />There is <a href='/admin/tours/pending' class='btn btn-warning'>pending</a> tours".html_safe
        end
    end
end

app/controllers/v1/pobs_controller.rb
class V1::PobsController < ApplicationController
  skip_before_filter :authenticate_by_token!

  def create_bundle
    @categories_list = params[:categories]
    @tour_id         = params[:tour_id]

    @se = params[:se]
    @nw = params[:nw]

    if @se.blank? || @nw.blank? || @tour_id.blank?
      render(:text => "failed", :status => 403) and return
    end

    @se = @se.split(',').map(&:to_f) # lat, lng
    @nw = @nw.split(',').map(&:to_f) # lat, lng

    @pobs = Pob.find_by_sql ["SELECT * FROM pobs LEFT JOIN pob_categories_pobs pcp ON pcp.pob_id = pobs.id WHERE pcp.pob_category_id IN (?) AND pobs.latitude BETWEEN #{@se[0]} AND #{@nw[0]} AND pobs.longitude BETWEEN #{@nw[1]} AND #{@se[1]}", @categories_list.split(',').map{|c| c.to_i}]

puts "SELECT * FROM pobs WHERE pobs.latitude BETWEEN #{@se[0]} AND #{@nw[0]} AND pobs.longitude BETWEEN #{@nw[1]} AND #{@se[1]}"

puts Pob.find_by_sql("SELECT * FROM pobs WHERE pobs.latitude BETWEEN #{@se[0]} AND #{@nw[0]} AND pobs.longitude BETWEEN #{@nw[1]} AND #{@se[1]}").inspect


    pobs_bundle = PobsBundle.new

    pobs_bundle.south = @se[0]
    pobs_bundle.east = @se[1]
    pobs_bundle.north = @nw[0]
    pobs_bundle.west = @nw[1]

    pobs_bundle.pobs = @pobs.uniq
    pobs_bundle.tour_id = @tour_id
    pobs_bundle.categories_ids = @categories_list.split(',').map{|c| c.to_i}.compact.join(',')
    pobs_bundle.save

    render :text => 'success', :status => 200
  end

  def sync
    tour_ids = params[:tour_ids].split(',').map{|id| id.strip.to_i}
    timestamp = params[:timestamp]

    tours = Tour.find tour_ids

    if timestamp.blank? || tour_ids.blank? || tours.blank?
      render(:json => {:result => "failed"}.to_json, :status => 403) and return
    end

    @s3 = AWS::S3.new(
      :access_key_id     => S3_ACCESS_KEY,
      :secret_access_key => S3_SECRET
    )

    obj_urls = {}
    tours.map(&:get_last_pobs_bundle).compact.each do |last_pobs_bundle|
      if last_pobs_bundle.created_at.utc.to_i > timestamp.to_i
        obj = @s3.buckets[S3_POBS_BUCKET_NAME].objects[last_pobs_bundle.link_to_bundle.to_s]
        obj_urls[last_pobs_bundle.tour_id] = obj.url_for(:read, :secure => false, :expires => 1.year).to_s
      end
    end

    render :json => {:result => "success", :pobs_bundles_urls => obj_urls, :timestamp => Time.current.utc.to_i}.to_json
  rescue ActiveRecord::RecordNotFound => e
    render :json => {:result => "failed", :status => e.message}.to_json, :status => 404
  rescue => e
    render :json => {:result => "failed"}.to_json, :status => 403
  end
end

app/views/admin/pobs/_form.html.erb
  <%= error_messages_for :pob %>

  <%= f.full_error :name %>
  <%= f.input :name, :label => 'POBs title', :required => true %>

  <%= f.input :country, :as => :select, :collection => @countries, :required => true, :input_html => { :onchange => "jQuery('#pob_city').val(''); jQuery('#pob_address').val(''); zoom_to_selected_country_enable_city_disable_address()" } %>

  <%= f.input :city, :required => false %>
  <%= f.full_error :city %>

  <%= f.input :address  %>
  <%= f.full_error :address %>

  <%= f.input :longitude, :as => :float, :required => true %>
  <%= f.full_error :longitude %>

  <%= f.input :latitude, :as => :float, :required => true %>
  <%= f.full_error :latitude %>

  <%= f.input :open_hours, :label => 'Working hours', :required => false %>
  <%= f.full_error :open_hours %>

  <%= f.input :url, :label => 'Website', :required => false %>
  <%= f.full_error :url %>

  <%= f.input :email, :label => 'Email', :required => false %>
  <%= f.full_error :email %>

  <%= f.input :phone, :label => 'Phone', :required => false %>
  <%= f.full_error :phone %>

  <%= f.input :price_range, :label => 'Price range', :required => false %>
  <%= f.full_error :price_range %>

  <%= f.full_error :pob_categories %>
  <div class="control-group check_boxes required">
    <label class="check_boxes required control-label"><abbr title="required">*</abbr> Pob categories</label>
    <div class="controls">
    <% @top_categories.each do |top_category| %>
      <label class="checkbox">
        <input class="check_boxes required" id="pob_pob_category_ids_<%= top_category.id %>" name="pob[pob_category_ids][]" type="checkbox" value="<%= top_category.id %>" <%= 'checked="checked"' if @pob.pob_category_ids.include?(top_category.id) %> onclick="toggle_subcategories('<%= top_category.id %>')"><%= top_category.name %>
      </label>
      <% top_category.subcategories.each do |subcategory| %>
      <label class="checkbox" style="margin-left:20px">
        <input class="check_boxes required <%= top_category.id %>_subcategories" id="pob_pob_category_ids_<%= subcategory.id %>" name="pob[pob_category_ids][]" type="checkbox" <%= 'checked="checked"' if @pob.pob_category_ids.include?(subcategory.id) %> value="<%= subcategory.id %>" onclick="disable_top_category_if_subcats_unchecked('<%= top_category.id %>')"><%= subcategory.name %>
      </label>
      <% end %>  
    <% end %>
    </div>
  </div>

  <%= f.input :description, :required => false %>
  <%= f.full_error :description %>

  <% if @pob.icon && @pob.icon_url %>
    <%= image_tag(@pob.icon_url) %>
  <% end %>

  <%= f.input :icon, :as => :file, :label => 'Thumbnail', :required => false %>
  <%= f.full_error :icon %>


  <%= f.input :txt_file, :as => :file, :label => 'Txt file', :required => false %>
  <%= f.full_error :icon %>
  <% if @pob.txt_file %>
    <span style="margin-left: 180px;"><%= @pob.txt_file.url %></span>
  <% end %>

  <%= f.hidden_field :icon_cache %>

  <% @pob.pob_images.build if @pob.pob_images.blank? %>

  <p style="font-size:18px;text-align:center;margin-top:40px;">POB images</p>

  <%= f.simple_fields_for(@pob.pob_images.blank? ? :pob_images : @pob.pob_images.first) do |pob_images_f| %>
    <% (1..5).map do |i| %>
    <% pob_image_id = @pob.pob_images.try(:[], i).nil? ? i : @pob.pob_images.try(:[], i).id %>
    <div style="padding:5px;border:1px solid #ccc;margin:5px;">
      <p style="float:right"><%= link_to "X", 'javascript:void(0)', :onclick => "delete_pob_image(#{pob_image_id})" %></p>

      <p style="font-size:18px;">#<%= i %></p>
      <% if ! @pob.pob_images.try(:[], i).try(:image_url).blank? %>
      <div style="margin:10px;float:left" id="pob_image_image_<%= pob_image_id %>">
        <%= image_tag(@pob.pob_images[i].image_url(:smaller_thumb)) %>
      </div>
      <% end %>

      <%= pob_images_f.input :image, :as => :file, :required => false, :input_html => { :id => "pob_image_input_#{pob_image_id}", :name => "pob[pob_images_attributes][#{pob_image_id}][image]"} %>
      <%#= pob_images_f.hidden_field :image_cache, :id => "pob_image_cache_#{i}" %>
    </div>
    <% end %>
  <% end %>

  <%= f.button :submit %>
  <%= link_to 'Cancel', session[:return_to_pob], {:class => "btn btn-info"} %>  

app/views/admin/pobs/edit.html.erb
<link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.4/leaflet.css" />
<!--[if lte IE 8]>
  <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.4/leaflet.ie.css" />
<![endif]-->

<script src="http://cdn.leafletjs.com/leaflet-0.4/leaflet.js"></script>

<h2 style="text-align:center">Update "<%= @pob.name %>" POB</h2>

<div id="leaflet_map"></div>

<%= simple_form_for([:admin, @pob], :validate => true, :html => {:multipart => true, :class => 'form-horizontal', :style => "width:420px;float:left" }) do |f| %>
  <%= render :partial => "admin/pobs/form", :locals => {:f => f} %>
<% end %>

app/views/admin/pobs/index.html.erb
<div class="left">
  <%= form_tag "/admin/pobs/search", :method => :get do -%>
    <div class="filter">
      <div class="row">
        <div class="span1">Name:</div><div class="span3"><%= text_field_tag 'pob[name]', @pob_name %></div>
        <div class="span1">City:</div><div class="span3"><%= text_field_tag 'pob[city]', @pob_city %></div>
        <div class="span1"><%= submit_tag "Filter", :class => "btn btn-primary" %></div>
        <div class="span1"><%= submit_tag "Reset", :onclick => "reset_pob_filter(); return false;", :class => "btn btn-danger" %></div>
      </div>
      <div class="row">
        <div class="span1">Country:</div><div class="span3"><%= select_tag('pob[country]', options_for_select(@countries, @pob_country), :include_blank => true) %></div>
        <div class="span1">Category:</div><div class="span3"><%= select_tag 'pob[category]', options_from_collection_for_select(PobCategory.all, "id", "name", @pob_category), {:multiple => true} %></div>
        <div class="span3">
          <a href="/admin/pobs/coupons/search">Search coupons</a><br />
          <a href="/admin/pobs/banners/search">Search banners</a>
        </div>
      </div>
    </div>
    <div class="clear"></div>
  <% end -%>
 
  <h2 style="text-align:center">POBs count: <%= @pobs_count %></h2>

  <div style="float:right">
    <%= link_to "Create new POB", new_admin_pob_path, :class => "btn btn-primary" %>
  </div>

  <%= will_paginate @pobs, :params => {:pob => {:country => @pob_country, :name => @pob_name, :city => @pob_city, :category => @pob_category}} %>

  <table class="table table-striped">
    <thead>
      <th>#</th>
      <th>Name</th>
      <th>Country/City</th>
      <th>Categories</th>
      <th>Action</th>
    </thead>
    <tbody>
      <% @pobs.each do |pob| %>
      <tr>
        <td><%= pob.id %></td>
        <td><%= link_to pob.name, admin_pob_path(pob) %></td>
        <td><%= pob.country %> / <%= pob.city %></td>
        <td><%= pob.pob_categories.map{|cat| cat.name}.join(', ') %></td>
        <td><%= link_to "Edit", edit_admin_pob_path(pob), :class => "btn btn-info" %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <%= will_paginate @pobs %>
</div>

app/views/admin/pobs/new.html.erb
<link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.4/leaflet.css" />
<!--[if lte IE 8]>
  <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.4/leaflet.ie.css" />
<![endif]-->

<script src="http://cdn.leafletjs.com/leaflet-0.4/leaflet.js"></script>

<h2 style="text-align:center">Create new POB</h2>

<div id="leaflet_map"></div>

<%= simple_form_for([:admin, @pob], :validate => true, :html => {:multipart => true, :class => 'form-horizontal', :style => "width:420px;float:left" }) do |f| %>
  <%= render :partial => "admin/pobs/form", :locals => {:f => f} %>
<% end %>

app/views/admin/pobs/show.html.erb
<link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.4/leaflet.css" />
<!--[if lte IE 8]>
  <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.4/leaflet.ie.css" />
<![endif]-->

<script src="http://cdn.leafletjs.com/leaflet-0.4/leaflet.js"></script>

<div style="float:left;width:420px">
  <div class="row">
    <div class="span2">Name</div>
    <div class="span2"><%= @pob.name %></div>
  </div>

  <div class="row">
    <div class="span2">Country</div>
    <div class="span2"><%= @pob.country %></div>
  </div>

  <div class="row">
    <div class="span2">City</div>
    <div class="span2"><%= @pob.city %></div>
  </div>

  <div class="row">
    <div class="span2">Address</div>
    <div class="span2"><%= @pob.address %></div>
  </div>

  <div class="row">
    <div class="span2">Description</div>
    <div class="span2"><%= @pob.description %></div>
  </div>

  <div class="row">
    <div class="span2">Categories</div>
    <div class="span2"><%= @pob.pob_categories.map{|c| c.name}.join(', ') %></div>
  </div>

  <div class="row">
    <div class="span2">Longitude</div>
    <div class="span2"><%= @pob.longitude %></div>
  </div>

  <div class="row">
    <div class="span2">Latitude</div>
    <div class="span2"><%= @pob.latitude %></div>
  </div>

  <input type="hidden" id="pob_longitude" value="<%= @pob.longitude %>"/>
  <input type="hidden" id="pob_latitude" value="<%= @pob.latitude %>"/>

  <% if !@pob.icon.blank? %>
  <div class="row">
    <div class="span2">Icon</div>
    <div class="span2"><%= image_tag(@pob.icon_url) %></div>
  </div>
  <% end %>

  <% if @pob.pob_images.any? %>
    <% @pob.pob_images.each_with_index do |pob_image, i| %>
    <div class="row">
      <div class="span2">Pob Image #<%=(i+1)%></div>
      <div class="span2"><%= image_tag(pob_image.image_url) %></div>
    </div>
    <% end %>
  <% end %>

  <%= link_to "Edit", edit_admin_pob_path(@pob), :class => "btn btn-primary" %>
  <%= link_to "Manage coupons", admin_pob_coupons_path(@pob), :class => "btn btn-success" %>
  <%= link_to "Manage banners", admin_pob_banners_path(@pob), :class => "btn btn-success" %>
  <%= link_to "Delete", admin_pob_path(@pob), :method => :delete, :confirm => "Are you sure you want to delete this POB?", :class => "btn btn-danger" %>
</div>

<div id="leaflet_map"></div>