config/routes.rb
MarketApi::Application.routes.draw do
  get '/login' => 'v1/market#login'
  match '/auth/:provider/callback' => 'v1/sessions#create'
  post 'sessions/create' => "v1/sessions#create"

  get "/users/return_token", :to => "v1/users#return_token",          :as => "users_return_token"
  get "/users/check_logged_in", :to => "v1/users#check_logged_in",    :as => "check_logged_in"

  devise_for :users, :controllers => {:registrations => "v1/registrations", :sessions => "v1/my_devise_sessions"}

  namespace :admin do
    match "login/change" => "login#change"
    match "logout" => "login#destroy"

    resources :login

    match "pobs/search", :to => "pobs#search"
    resources :pobs do
      resources :coupons
      resources :banners
    end
    match "pobs/coupons/search", :to => "coupons#search"
    match "pobs/banners/search", :to => "banners#search"
    match "pobs/remove_pob_image/:pob_image_id", :to => "pobs#remove_pob_image"

    match "tours/:type/show_tours/:page", :to => "tours#show_tours", :as => "tours_show_tours"
    match "tours/pending", :to => "tours#pending"
    match "tours/rebuild_bundles", :to => "tours#rebuild_bundles"
    resources :tours do
      member do
        post :free
        post :paid
        post :publish
        post :unpublish
      end
    end

    match "clients/:id/save_tours", :to => "clients#save_tours", :as => "clients_save_tours"
    match "clients/:id/generate_users", :to => "clients#generate_users", :as => "clients_generate_users"
    match "clients/:id/show_users/:page", :to => "clients#show_users", :as => "clients_show_users"

    match "clients/check_name_validity", :to => "clients#check_name_validity"
    match "clients/check_password_validity", :to => "clients#check_password_validity"
    match "clients/check_email_validity", :to => "clients#check_email_validity"

    match "clients/:id/download_csv_userlist(/:generation)", :to => "clients#download_csv_userlist", :as => "clients_download_csv_userlist"
    match "clients/:id/download_pdf_userlist(/:generation)", :to => "clients#download_pdf_userlist", :as => "clients_download_pdf_userlist"

    resources :clients

    match "users/:type/show_users/:page", :to => "users#show_users", :as => "users_show_users"
    
    resources :users do
      resources :orders
    end

    resource :dashboard

    resource :statistics, :only => [] do
      member do
        get :top_buyers
        get :top_popular_tours
      end
    end
    root :to => 'dashboard#index'
  end

  namespace :v1 do
    namespace :ios do
      resources :orders, :only => :create
    end
    namespace :android do
      resources :orders, :only => :create
    end
    
    resources :orders, :only => [:index, :show]
    resources :places, :only => :index
    resources :clients, :only => :index
    resources :pob_categories, :only => :index
  end

  get '/pobs/create_bundle' => "v1/pobs#create_bundle"
  get '/pobs/sync' => "v1/pobs#sync"

  get '/market/places/:country/:city.xml' => "v1/market#show",               :as => "market_country_city"
  get '/market/places/:country.xml' => "v1/market#show"
  get '/market/places.xml' => "v1/market#index"

  match "/products/map/:id.:format" => "v1/products#map",                    :as => "map_market_product"
  match "/products/media/:id.:format" => "v1/products#media",                :as => "media_market_product"
  match "/products/:id.:format" => "v1/products#show",                       :as => "market_product"

  root :to => "admin/dashboard#index"
end

app/models/tour.rb
class Tour < ActiveRecord::Base
  has_many :orders
  has_many :pobs_bundles

  belongs_to :client

  attr_accessible :id, :city, :name, :country, :build_id, :url, :client_id, :is_ubertour, :subtours_count

  has_many :tour_ubertours, :foreign_key => "ubertour_id"
  has_many :children, :through => :tour_ubertours, :source => :tour

  scope :top_popular, lambda { |*args| where('orders_count > 0').order('orders_count DESC').limit(args.blank? ? nil : args.pop) }
  scope :regular, -> { where('is_ubertour = ?', false) }
  scope :ubertours, -> { where('is_ubertour = ?', true) }

  include AASM

  aasm_state :initial
  aasm_state :pobs_bundled
  aasm_state :edited

  aasm_initial_state :initial

  aasm_event :pobs_bundled do
    transitions :from => [:edited, :initial], :to => :pobs_bundled
  end

  aasm_event :touch do
    transitions :from => [:initial, :pobs_bundled, :edited], :to => :edited
  end

  def get_last_pobs_bundle
    self.pobs_bundles.sort{|n,m| n.id <=> m.id}.last
  end
end

app/controllers/admin/tours_controller.rb
class Admin::ToursController < Admin::ApplicationController
  NUM_OF_TOURS_PER_PAGE = 30

  before_filter :paginated_tours, :only => [:index, :show_tours]

  def index
    @tours = @tours_tmp.limit(NUM_OF_TOURS_PER_PAGE)
  end
  
  def show_tours
    @tours = @tours_tmp.limit(NUM_OF_TOURS_PER_PAGE).offset((@current_page.to_i - 1) * NUM_OF_TOURS_PER_PAGE).all # we need all here since it'll be no records displayed
  end

  def free
    @tour = Tour.find(params[:id])
    @tour.update_attribute(:free, true)
  end
  
  def paid
    @tour = Tour.find(params[:id])
    @tour.update_attribute(:free, false)
  end

  def publish
    @tour = Tour.find(params[:id])
    @tour.update_attribute(:is_published, true)
    respond_to do |format|
      format.json { render :json=> [] }
    end
  end

  def unpublish
    @tour = Tour.find(params[:id])
    @tour.update_attribute(:is_published, false)
    respond_to do |format|
      format.json { render :json=> [] }
    end
  end

  def pending
    @tours = Tour.edited
  end

  def rebuild_bundles
    @tours = Tour.find(params[:tours] || [])
    @tours.each do |tour|
      pobs_bundle = PobsBundle.find_last_by_tour_id(tour.id)
      if pobs_bundle.south && pobs_bundle.north && pobs_bundle.west && pobs_bundle.east
        pobs_bundles_categories_ids = pobs_bundle.filtered_categories

        @pobs = Pob.find_by_sql ["SELECT * FROM pobs LEFT JOIN pob_categories_pobs pcp ON pcp.pob_id = pobs.id WHERE pcp.pob_category_id IN (?) AND pobs.latitude >= #{pobs_bundle.south} AND pobs.latitude <= #{pobs_bundle.north} AND pobs.longitude >= #{pobs_bundle.west} AND pobs.longitude <= #{pobs_bundle.east} GROUP BY pobs.id", pobs_bundles_categories_ids]
        new_pobs_bundle = pobs_bundle.clone
        new_pobs_bundle.created_at = Time.now
        new_pobs_bundle.pobs = @pobs
        new_pobs_bundle.save
      end
      tour.try(:pobs_bundled!)
      tour.save
    end
    flash[:notice] = "You've successfully updated tours."
    redirect_to admin_tours_url
  end

  def filter_draft_categories
  end

  protected
    def paginated_tours
      @current_page = params[:page] || 1
      @type = params[:type] || 'all'

      @tours_tmp = case @type
        when 'regular'; Tour.regular.order("created_at DESC")
        when 'all'; Tour.order("created_at DESC")
        when 'ubertours'; Tour.ubertours.order("created_at DESC")
      end
      
      @total_tours = @tours_tmp.count
      @num_of_pages = (@total_tours / NUM_OF_TOURS_PER_PAGE.to_f).ceil
    end
end

app/views/admin/tours/_free.html.haml
= link_to "Mark as Free", free_admin_tour_path(tour), :remote => true, :method => :post, :class => 'btn btn-success'

app/views/admin/tours/_paid.html.haml
= link_to "Mark as Paid", paid_admin_tour_path(tour), :remote => true, :method => :post, :class => 'btn btn-danger'

app/views/admin/tours/_tour.html.haml
%tr
  %td
    = tour.id
  %td
    = tour.name
    - if tour.is_ubertour
      %span{:style=>"color:red;font-weight:bold;"} [Ubertour]
  %td
    = tour.orders_count
  %td
    = tour.get_last_pobs_bundle.try(:pobs).try(:count)
  %td{:id => "action_#{tour.id}"}
    - if tour.free?
      = render :partial => 'paid', :locals => {:tour => tour}
    - else
      = render :partial => 'free', :locals => {:tour => tour}
  %td.is_published
    = check_box_tag "is_published_#{tour.id}", tour.id, tour.is_published
    
    

app/views/admin/tours/_tours_core.html.erb
<table class="table table-striped">
  <% unless @tours.empty? %>
    <thead>
      <tr>
        <th class="tour_id">ID</td>
        <th>Tour</td>
        <th># of orders</td>
        <th># of POBs in last bundle</td>
        <th class="tour_actions">Action</td>
        <th class="tour_actions">Published on GP</td>
      </tr>
    </thead>
    <tbody>
      <% @tours.each do |tour| %>
        <%= render :partial => 'tour', :object => tour %>
      <% end %>
    </tbody>
  <% end %>
</table>
<%= hidden_field_tag 'auth_token', form_authenticity_token %>

<% if @total_tours > Admin::ToursController::NUM_OF_TOURS_PER_PAGE %>
<div class="pagination">
  <ul>
    <li class="prev <%= @current_page.to_i == 1 ? 'disabled' : '' %>">
      <% if @current_page.to_i == 1 %>
        <a href="javascript:void(0)">&larr; Previous</a>
      <% else %>
        <%= link_to raw('&larr; Previous'), admin_tours_show_tours_path(@type, @current_page.to_i - 1), {:remote => true} %>
      <% end %>
    </li>
    <% before_ellipsis, after_ellipsis = false, false %>
    <% @num_of_pages.times do |i| %>
      <% if ((i < (@current_page.to_i-4)) && !(0..2).include?(i)) %>
        <% if ! before_ellipsis %>
          <% before_ellipsis = true %>
          <li class="disabled"><a href="#">...</a></li>
        <% end %>
      <% elsif ((i > (@current_page.to_i+2)) && !((@num_of_pages-3)..@num_of_pages).include?(i)) %>
        <% if ! after_ellipsis %>
          <% after_ellipsis = true %>
          <li class="disabled"><a href="#">...</a></li>          
        <% end %>
      <% else %>
        <li <%= (@current_page.to_i == (i+1)) ? "class=active" : '' %>><%= link_to (i + 1), admin_tours_show_tours_path(@type, i+1), {:remote => true} %></li>
      <% end %>
    <% end %>
    <li class="next <%= @current_page.to_i == @num_of_pages ? 'disabled' : '' %>">
      <% if @current_page.to_i == @num_of_pages %>
        <a href="javascript:void(0)">Next &rarr;</a>
      <% else %>
        <%= link_to raw('Next &rarr;'), admin_tours_show_tours_path(@type, @current_page.to_i + 1), {:remote => true} %>
      <% end %>
    </li>
  </ul>
</div>
<% end %>

app/views/admin/tours/index.html.erb
<ul class="breadcrumb">
  <li>
    <%= link_to 'Dashboard', admin_root_url %>
    <span class="divider"> / </span>
  </li>
  <li class="active">Tours</li>
</ul>

<div class="tour-type-switch">
  <a class="btn <%= (@type == 'all' ? 'active' : '') %>" href="?type=all">All</a>
  <a class="btn <%= (@type == 'regular' ? 'active' : '') %>" href="?type=regular">Regular</a>
  <a class="btn <%= (@type == 'ubertours' ? 'active' : '') %>" href="?type=ubertours">Ubertours</a>
  <a class="btn btn-warning" href="/admin/tours/pending">Pending</a>
</div>

<div id="tours_container">
  <%= render :partial => "tours_core" %>
</div>

app/views/admin/tours/pending.html.erb
<ul class="breadcrumb">
  <li>
    <a href="/admin">Dashboard</a>
    <span class="divider">/</span>
  </li>
  <li class="active">
    <%= link_to 'Tours', admin_tours_url %>
    <span class="divider">/</span>
  </li>
  <li class="active">Pending tours</li>
</ul>
<div class="left">
  <% if @tours.count > 0 %>
  POBs were changed and following tours were affected.
  <form action="/admin/tours/rebuild_bundles" method="get" id="pending_tours">
    <table class="table table-striped">
      <thead>
        <th>Check</th>
        <th style="width: 90%;">Name</th>
      </thead>
      <tbody>
        <% @tours.each do |tour| %>
        <tr>
          <td><input type="checkbox" name="tours[]" value="<%= tour.id %>" /></td>
          <td><%= tour.name %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <div class"row" style="margin-bottom: 10px;"><a href="#" onclick="return toggle_pending_tours_checkboxes(true);">Select all</a> / <a href="#" onclick="return toggle_pending_tours_checkboxes(false);">Unselect all</a></div>
    <p><%= submit_tag "Update selected", :class => "btn btn-primary" %></p>
  </form>
  <% else %>
    No pending tours
  <% end %>
</div>

app/views/admin/tours/show_tours.js.erb
jQuery('#tours_container').html('<%= escape_javascript(render(:partial => 'tours_core')) %>');