config/routes.rb
MarketApi::Application.routes.draw do
  get '/login' => 'v1/market#login'
  match '/auth/:provider/callback' => 'v1/sessions#create'
  post 'sessions/create' => "v1/sessions#create"

  get "/users/return_token", :to => "v1/users#return_token",          :as => "users_return_token"
  get "/users/check_logged_in", :to => "v1/users#check_logged_in",    :as => "check_logged_in"

  devise_for :users, :controllers => {:registrations => "v1/registrations", :sessions => "v1/my_devise_sessions"}

  namespace :admin do
    match "login/change" => "login#change"
    match "logout" => "login#destroy"

    resources :login

    match "pobs/search", :to => "pobs#search"
    resources :pobs do
      resources :coupons
      resources :banners
    end
    match "pobs/coupons/search", :to => "coupons#search"
    match "pobs/banners/search", :to => "banners#search"
    match "pobs/remove_pob_image/:pob_image_id", :to => "pobs#remove_pob_image"

    match "tours/:type/show_tours/:page", :to => "tours#show_tours", :as => "tours_show_tours"
    match "tours/pending", :to => "tours#pending"
    match "tours/rebuild_bundles", :to => "tours#rebuild_bundles"
    resources :tours do
      member do
        post :free
        post :paid
        post :publish
        post :unpublish
      end
    end

    match "clients/:id/save_tours", :to => "clients#save_tours", :as => "clients_save_tours"
    match "clients/:id/generate_users", :to => "clients#generate_users", :as => "clients_generate_users"
    match "clients/:id/show_users/:page", :to => "clients#show_users", :as => "clients_show_users"

    match "clients/check_name_validity", :to => "clients#check_name_validity"
    match "clients/check_password_validity", :to => "clients#check_password_validity"
    match "clients/check_email_validity", :to => "clients#check_email_validity"

    match "clients/:id/download_csv_userlist(/:generation)", :to => "clients#download_csv_userlist", :as => "clients_download_csv_userlist"
    match "clients/:id/download_pdf_userlist(/:generation)", :to => "clients#download_pdf_userlist", :as => "clients_download_pdf_userlist"

    resources :clients

    match "users/:type/show_users/:page", :to => "users#show_users", :as => "users_show_users"
    
    resources :users do
      resources :orders
    end

    resource :dashboard

    resource :statistics, :only => [] do
      member do
        get :top_buyers
        get :top_popular_tours
      end
    end
    root :to => 'dashboard#index'
  end

  namespace :v1 do
    namespace :ios do
      resources :orders, :only => :create
    end
    namespace :android do
      resources :orders, :only => :create
    end
    
    resources :orders, :only => [:index, :show]
    resources :places, :only => :index
    resources :clients, :only => :index
    resources :pob_categories, :only => :index
  end

  get '/pobs/create_bundle' => "v1/pobs#create_bundle"
  get '/pobs/sync' => "v1/pobs#sync"

  get '/market/places/:country/:city.xml' => "v1/market#show",               :as => "market_country_city"
  get '/market/places/:country.xml' => "v1/market#show"
  get '/market/places.xml' => "v1/market#index"

  match "/products/map/:id.:format" => "v1/products#map",                    :as => "map_market_product"
  match "/products/media/:id.:format" => "v1/products#media",                :as => "media_market_product"
  match "/products/:id.:format" => "v1/products#show",                       :as => "market_product"

  root :to => "admin/dashboard#index"
end

app/models/coupon.rb
class Coupon < ActiveRecord::Base
  belongs_to :pob
  has_many :banners, :dependent => :destroy

  validates_associated :pob
  validates_presence_of :name, :image

  attr_accessible :name, :image, :image_url, :image_cache

  # carrierwave
  mount_uploader :image, CouponImageUploader

  after_save :find_affected_tours
  before_destroy :find_affected_tours

  def find_affected_tours
    self.pob.try(:find_affected_tours)
  end
end

app/controllers/admin/coupons_controller.rb
class Admin::CouponsController < Admin::ApplicationController

  before_filter :set_defaults

  def index
    @page = params[:page] || 1
    @coupons = Coupon.where(:pob_id => @pob.id).order('created_at DESC').paginate(:page => @page, :per_page => 30)
    @coupons_count = Coupon.count
  end

  def new
    @coupon = Coupon.new
    session[:return_to_coupons] = request.env["HTTP_REFERER"] || admin_pob_coupons_path(@pob)
  end

  def show
  end

  def search 
    relation = Coupon
    if params[:coupon]
      @coupon_name = params[:coupon][:name]
      relation = @coupon_name.blank? ? relation : relation.where(['coupons.name LIKE ?', "%#{@coupon_name}%"])
    end

    @page = params[:page] || 1
    @coupons_count = relation.count
    @coupons = relation.paginate(:page => @page, :per_page => 30)
  end

  def create
    @coupon = Coupon.new(params[:coupon])  
    @coupon.pob_id = @pob.id
    if !@coupon.save
      flash.now[:error] = "Sorry, there were errors while creating new coupon"
      render(:action => :new)
    else
      set_flash_notice @coupon, "created"
      redirect_to admin_pob_coupons_path
    end
  end

  def edit
    @coupon = Coupon.find params[:id]
    session[:return_to_coupons] = request.env["HTTP_REFERER"] || admin_pob_coupons_path(@pob)
  end

  def update
      @coupon = Coupon.find(params[:id])
      @coupon.pob_id = @pob.id
      if @coupon.update_attributes(params[:coupon])
        set_flash_notice @coupon, "updated"
        redirect_to session[:return_to_coupons]
      else
        flash.now[:error] = "Sorry, there were errors while updating #{@coupon.name}"
        render(:action => :edit)
      end
  end

  def destroy
    @coupon = Coupon.find params[:id]
    if @coupon.destroy
      set_flash_notice @coupon, "deleted"
      redirect_to admin_pob_coupons_url
    else
      flash[:error] = "Sorry, there were errors while deleting coupon called #{@pob.name}"
      redirect_to(:back)
    end
  end
 
  private
    def set_defaults
      if params[:pob_id]
        @pob = Pob.find params[:pob_id]
      end
    end

    def set_flash_notice(coupon, action)
        flash[:notice] = "You've successfully #{action} coupon called #{coupon.name}. ".html_safe
        if Tour.edited.count > 0
          flash[:notice] << "<br />There is <a href='/admin/tours/pending' class='btn btn-warning'>pending</a> tours".html_safe
        end
    end
end

app/views/admin/coupons/_form.html.erb
  <%= error_messages_for :coupon %>

  <%= f.full_error :name %>
  <%= f.input :name, :label => 'Coupon name', :required => true %>

  <%= f.input :image, :as => :file, :required => true %>
  <%= f.full_error :image %>

  <div class="image_wrapper">
    <% if @coupon.image && @coupon.image_url %>
      <%= image_tag @coupon.image_url, :style => 'margin: 0 0 20px 100px;' %>
    <% end %>
  </div>

  <%= f.button :submit %>
  <%= link_to 'Cancel', session[:return_to_coupons], {:class => "btn btn-info"} %>  

app/views/admin/coupons/edit.html.erb
<ul class="breadcrumb">
  <li>
    <a href="/admin">Dashboard</a>
    <span class="divider">/</span>
  </li>
  <li class="active">
    <%= link_to @pob.name, admin_pob_path(@pob) %>
    <span class="divider">/</span>
  </li>
  <li class="active">
    <%= link_to 'Coupons', admin_pob_coupons_path(@pob) %>
    <span class="divider">/</span>
  </li>
  <li class="active">Edit <%= @coupon.name %></li>
</ul>
<%= simple_form_for([:admin, @pob, @coupon], :validate => true, :html => {:multipart => true, :class => 'form-horizontal', :style => "width:420px;float:left" }) do |f| %>
  <%= render :partial => "admin/coupons/form", :locals => {:f => f} %>
<% end %>

app/views/admin/coupons/index.html.erb
<ul class="breadcrumb">
  <li>
    <a href="/admin">Dashboard</a>
    <span class="divider">/</span>
  </li>
  <li class="active">
    <%= link_to @pob.name, admin_pob_path(@pob) %>
    <span class="divider">/</span>
  </li>
  <li class="active">Coupons</li>
</ul>
<div style="float:right">
  <%= link_to "Create new coupon", new_admin_pob_coupon_path, :class => "btn btn-primary" %>
</div>
<div class="left">
  <table class="table table-striped">
    <thead>
      <th>#</th>
      <th>Name</th>
      <th width="150px">Action</th>
    </thead>
    <tbody>
      <% @coupons.each do |coupon| %>
      <tr>
        <td><%= coupon.id %></td>
        <td><%= link_to coupon.name, edit_admin_pob_coupon_path(@pob, coupon) %></td>
        <td>
          <%= link_to "Edit", edit_admin_pob_coupon_path(@pob, coupon), :class => "btn btn-info" %>
          <%= link_to "Delete", admin_pob_coupon_path(@pob, coupon), :method => :delete, :confirm => "Are you sure you want to delete this coupon?", :class => "btn btn-danger" %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <%= will_paginate @coupons %>
</div>

app/views/admin/coupons/new.html.erb
<ul class="breadcrumb">
  <li>
    <a href="/admin">Dashboard</a>
    <span class="divider">/</span>
  </li>
  <li class="active">
    <%= link_to @pob.name, admin_pob_path(@pob) %>
    <span class="divider">/</span>
  </li>
  <li class="active">
    <%= link_to 'Coupons', admin_pob_coupons_path(@pob) %>
    <span class="divider">/</span>
  </li>
  <li class="active">Create new coupon</li>
</ul>
<%= simple_form_for([:admin, @pob, @coupon], :validate => true, :html => {:multipart => true, :class => 'form-horizontal', :style => "width:420px;float:left" }) do |f| %>
  <%= render :partial => "admin/coupons/form", :locals => {:f => f} %>
<% end %>

app/views/admin/coupons/search.html.erb
<ul class="breadcrumb">
  <li>
    <a href="/admin">Dashboard</a>
    <span class="divider">/</span>
  </li>
  <li>
    <%= link_to 'Pobs', admin_pobs_url %>
    <span class="divider">/</span>
  </li>
  <li class="active">Search coupons</li>
</ul>
<div class="left">
  <%= form_tag "/admin/pobs/coupons/search", :method => :get do -%>
    <div class="filter">
      <div class="row">
        <div class="span1">Name: </div><div class="span3"><%= text_field_tag 'coupon[name]', @coupon_name %></div>
        <div class="span1"><%= submit_tag "Filter", :class => "btn btn-primary" %></div>
        <div class="span1"><a href="/admin/pobs/coupons/search" class="btn btn-danger">Reset</a></div>
      </div>
    </div>
    <div class="clear"></div>
  <% end -%>
  <h2 style="text-align:center">Coupons count: <%= @coupons_count %></h2>
  <table class="table table-striped">
    <thead>
      <th>#</th>
      <th>Name</th>
      <th>Pob</th>
      <th>Action</th>
    </thead>
    <tbody>
      <% @coupons.each do |coupon| %>
      <tr>
        <td><%= coupon.id %></td>
        <td><%= link_to(coupon.name, edit_admin_pob_coupon_path(coupon.pob, coupon)) if coupon.pob %></td>
        <td><%= link_to(coupon.pob.name, admin_pob_path(coupon.pob)) if coupon.pob %></td>
        <td><%= link_to("Edit", edit_admin_pob_coupon_path(coupon.pob, coupon), :class => "btn btn-info") if coupon.pob %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <%= will_paginate @coupons %>
</div>